name: blog_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  fpdart: ^1.1.0
  get_it: ^7.6.7
  go_router: ^13.2.1
  image_picker: ^1.0.7
  supabase: ^2.0.8
  supabase_flutter: ^2.3.4
  uuid: ^4.3.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
